(in-package :sem-map-utils)

(defparameter *mesh-path-whitelist*
  '(
    "package://robcog/IAIOven/IAIOven.dae"
 "package://robcog/IAIFridgeDoor/IAIFridgeDoor.dae"
 "package://robcog/IAIFridgeDoor/IAIFridgeDoor.dae"
 "package://robcog/IAIFridgeDoor/IAIFridgeDoor.dae"
 "package://robcog/IAIFridgeDrawer/IAIFridgeDrawer.dae"
;; "package://robcog/IAIOvenDoor/IAIOvenDoor.dae"
 "package://robcog/IAIOvenDrawerMiddleBottom/IAIOvenDrawerMiddleBottom.dae"
 "package://robcog/IAIOvenDrawerMiddleTop/IAIOvenDrawerMiddleTop.dae"
 "package://robcog/IAIOven/IAIOven.dae"
 "package://robcog/IAISinkDrawerLeftBottom/IAISinkDrawerLeftBottom.dae"
 "package://robcog/IAISinkDrawerLeftMiddle/IAISinkDrawerLeftMiddle.dae"
 "package://robcog/IAISinkDrawerLeftTop/IAISinkDrawerLeftTop.dae"
 "package://robcog/IAIBaerenMarkeFrischeAlpenmilch18/IAIBaerenMarkeFrischeAlpenmilch18.dae"
 "package://robcog/IAIBaerenMarkeFrischeAlpenmilch38/IAIBaerenMarkeFrischeAlpenmilch38.dae"
 "package://robcog/IAIBaerenMarkeFrischeKakao/IAIBaerenMarkeFrischeKakao.dae"
 "package://robcog/IAIBowlLarge/IAIBowlLarge.dae"
 "package://robcog/IAIBowlSmall/IAIBowlSmall.dae"
 "package://robcog/IAIBowl/IAIBowl.dae"
 "package://robcog/IAIBrandtVollkornZwieback/IAIBrandtVollkornZwieback.dae"
 "package://robcog/IAIButtonCooktopBottomLeft/IAIButtonCooktopBottomLeft.dae"
 "package://robcog/IAIButtonCooktopBottomRight/IAIButtonCooktopBottomRight.dae"
 "package://robcog/IAIButtonCooktopTopLeft/IAIButtonCooktopTopLeft.dae"
 "package://robcog/IAIButtonCooktopTopRight/IAIButtonCooktopTopRight.dae"
 "package://robcog/IAIButtonOven/IAIButtonOven.dae"
 "package://robcog/IAICooktopHeatingElementBottomLeft/IAICooktopHeatingElementBottomLeft.dae"
 "package://robcog/IAICooktopHeatingElementBottomRight/IAICooktopHeatingElementBottomRight.dae"
 "package://robcog/IAICooktopHeatingElementTopLeft/IAICooktopHeatingElementTopLeft.dae"
 "package://robcog/IAICooktopHeatingElementTopRight/IAICooktopHeatingElementTopRight.dae"
;; "package://robcog/IAICooktop/IAICooktop.dae"
 "package://robcog/IAICupEspresso/IAICupEspresso.dae"
 "package://robcog/IAICup/IAICup.dae"
 "package://robcog/IAIDiningTable/IAIDiningTable.dae"
;; "package://robcog/IAIDishwasherDoorHandle/IAIDishwasherDoorHandle.dae"
;; "package://robcog/IAIDishwasherDoor/IAIDishwasherDoor.dae"
 "package://robcog/IAIDishwasherLowerRack/IAIDishwasherLowerRack.dae"
 "package://robcog/IAIDishwasherUpperRack/IAIDishwasherUpperRack.dae"
 "package://robcog/IAIDishwasher/IAIDishwasher.dae"
 "package://robcog/IAIFaucetBody/IAIFaucetBody.dae"
 "package://robcog/IAIFaucetHandle/IAIFaucetHandle.dae"
 "package://robcog/IAIFaucetSpout/IAIFaucetSpout.dae"
 "package://robcog/IAIForkDessert/IAIForkDessert.dae"
 "package://robcog/IAIForkDinner/IAIForkDinner.dae"
 "package://robcog/IAIFridgeArea/IAIFridgeArea.dae"
 "package://robcog/IAIFridgeDoorBottomShelf/IAIFridgeDoorBottomShelf.dae"
 "package://robcog/IAIFridgeDoorHandle/IAIFridgeDoorHandle.dae"
 "package://robcog/IAIFridgeDoorTopShelf/IAIFridgeDoorTopShelf.dae"
 "package://robcog/IAIFridgeDoor/IAIFridgeDoor.dae"
 "package://robcog/IAIFridgeDrawerHandle/IAIFridgeDrawerHandle.dae"
 "package://robcog/IAIFridgeDrawer/IAIFridgeDrawer.dae"
 "package://robcog/IAIFridgeGlassShelf/IAIFridgeGlassShelf.dae"
 "package://robcog/IAIFridgeHumidityDrawer/IAIFridgeHumidityDrawer.dae"
 "package://robcog/IAIFridgeShelf/IAIFridgeShelf.dae"
 "package://robcog/IAIFridge/IAIFridge.dae"
 "package://robcog/IAIGlassRedwine/IAIGlassRedwine.dae"
 "package://robcog/IAIGlassRound/IAIGlassRound.dae"
 "package://robcog/IAIGlassTall/IAIGlassTall.dae"
 "package://robcog/IAIGlassWhitewine/IAIGlassWhitewine.dae"
 "package://robcog/IAIHohesCOrange/IAIHohesCOrange.dae"
 "package://robcog/IAIIslandArea/IAIIslandArea.dae"
 "package://robcog/IAIIslandDrawerBottomLeftHandle/IAIIslandDrawerBottomLeftHandle.dae"
 "package://robcog/IAIIslandDrawerBottomLeft/IAIIslandDrawerBottomLeft.dae"
 "package://robcog/IAIIslandDrawerBottomMiddleHandle/IAIIslandDrawerBottomMiddleHandle.dae"
 "package://robcog/IAIIslandDrawerBottomMiddle/IAIIslandDrawerBottomMiddle.dae"
 "package://robcog/IAIIslandDrawerBottomRightHandle/IAIIslandDrawerBottomRightHandle.dae"
 "package://robcog/IAIIslandDrawerBottomRight/IAIIslandDrawerBottomRight.dae"
 "package://robcog/IAIIslandDrawerTopLeftHandle/IAIIslandDrawerTopLeftHandle.dae"
 "package://robcog/IAIIslandDrawerTopLeft/IAIIslandDrawerTopLeft.dae"
 "package://robcog/IAIIslandDrawerTopMiddleHandle/IAIIslandDrawerTopMiddleHandle.dae"
 "package://robcog/IAIIslandDrawerTopMiddle/IAIIslandDrawerTopMiddle.dae"
 "package://robcog/IAIIslandDrawerTopRightHandle/IAIIslandDrawerTopRightHandle.dae"
 "package://robcog/IAIIslandDrawerTopRight/IAIIslandDrawerTopRight.dae"
 "package://robcog/IAIJaNougatBits/IAIJaNougatBits.dae"
 "package://robcog/IAIKellogsCornFlakesOriginal/IAIKellogsCornFlakesOriginal.dae"
 "package://robcog/IAIKitchenSink/IAIKitchenSink.dae"
 "package://robcog/IAIKnifeButter/IAIKnifeButter.dae"
 "package://robcog/IAIKnifeTable/IAIKnifeTable.dae"
 "package://robcog/IAIKoellnMuesliCranberry/IAIKoellnMuesliCranberry.dae"
 "package://robcog/IAIMuellerFruchtButterMilchErdbeere/IAIMuellerFruchtButterMilchErdbeere.dae"
 "package://robcog/IAIMuellerFruchtButterMilchHimbeere/IAIMuellerFruchtButterMilchHimbeere.dae"
 "package://robcog/IAIMuellerFruchtButterMilchMultiVitamin/IAIMuellerFruchtButterMilchMultiVitamin.dae"
 "package://robcog/IAIMuellerReineButterMilch/IAIMuellerReineButterMilch.dae"
 "package://robcog/IAIOvenArea/IAIOvenArea.dae"
;; "package://robcog/IAIOvenDoorHandle/IAIOvenDoorHandle.dae"
;; "package://robcog/IAIOvenDoor/IAIOvenDoor.dae"
 "package://robcog/IAIOvenDrawerLeftHandle/IAIOvenDrawerLeftHandle.dae"
 "package://robcog/IAIOvenDrawerLeft/IAIOvenDrawerLeft.dae"
 "package://robcog/IAIOvenDrawerMiddleBottomHandle/IAIOvenDrawerMiddleBottomHandle.dae"
 "package://robcog/IAIOvenDrawerMiddleBottom/IAIOvenDrawerMiddleBottom.dae"
 "package://robcog/IAIOvenDrawerMiddleTopHandle/IAIOvenDrawerMiddleTopHandle.dae"
 "package://robcog/IAIOvenDrawerMiddleTop/IAIOvenDrawerMiddleTop.dae"
 "package://robcog/IAIOvenDrawerRightHandle/IAIOvenDrawerRightHandle.dae"
 "package://robcog/IAIOvenDrawerRight/IAIOvenDrawerRight.dae"
 "package://robcog/IAIOvenRack/IAIOvenRack.dae"
 "package://robcog/IAIOven/IAIOven.dae"
 "package://robcog/IAIPlateClassic16/IAIPlateClassic16.dae"
 "package://robcog/IAIPlateClassic26/IAIPlateClassic26.dae"
 "package://robcog/IAIPlateClassic28/IAIPlateClassic28.dae"
 "package://robcog/IAISaucer/IAISaucer.dae"
 "package://robcog/IAISinkAirGap/IAISinkAirGap.dae"
 "package://robcog/IAISinkArea/IAISinkArea.dae"
 "package://robcog/IAISinkDrawerLeftBottomHandle/IAISinkDrawerLeftBottomHandle.dae"
 "package://robcog/IAISinkDrawerLeftBottom/IAISinkDrawerLeftBottom.dae"
 "package://robcog/IAISinkDrawerLeftMiddleHandle/IAISinkDrawerLeftMiddleHandle.dae"
 "package://robcog/IAISinkDrawerLeftMiddle/IAISinkDrawerLeftMiddle.dae"
 "package://robcog/IAISinkDrawerLeftTopHandle/IAISinkDrawerLeftTopHandle.dae"
 "package://robcog/IAISinkDrawerLeftTop/IAISinkDrawerLeftTop.dae"
 "package://robcog/IAISinkStrainer/IAISinkStrainer.dae"
 "package://robcog/IAISpoonDessert/IAISpoonDessert.dae"
 "package://robcog/IAISpoonSoup/IAISpoonSoup.dae"
 "package://robcog/IAITrashDrawerHandle/IAITrashDrawerHandle.dae"
 "package://robcog/IAITrashDrawer/IAITrashDrawer.dae"
 "package://robcog/IAITray/IAITray.dae"
 "package://robcog/IAIWasaDelicateCrisp/IAIWasaDelicateCrisp.dae"))


(defparameter *old-mesh-path-whitelist*
  '("package://robcog/Oven.dae"
    "package://robcog/FridgeDoor.dae"
    "package://robcog/FridgeDoor.dae"
    "package://robcog/FridgeDoor.dae"
    "package://robcog/FridgeDrawer.dae"
    "package://robcog/OvenDoor.dae"
    "package://robcog/OvenDrawerMiddleBottom.dae"
    "package://robcog/OvenDrawerMiddleTop.dae"
    "package://robcog/Oven.dae"
    "package://robcog/SinkDrawerLeftBottom.dae"
    "package://robcog/SinkDrawerLeftMiddle.dae"
    "package://robcog/SinkDrawerLeftTop.dae"
    "package://robcog/BaerenMarkeFrischeAlpenmilch18.dae"
    "package://robcog/BaerenMarkeFrischeAlpenmilch38.dae"
    "package://robcog/BaerenMarkeFrischeKakao.dae"
    "package://robcog/BowlLarge.dae"
    "package://robcog/BowlSmall.dae"
    "package://robcog/Bowl.dae"
    "package://robcog/BrandtVollkornZwieback.dae"
    "package://robcog/ButtonCooktopBottomLeft.dae"
    "package://robcog/ButtonCooktopBottomRight.dae"
    "package://robcog/ButtonCooktopTopLeft.dae"
    "package://robcog/ButtonCooktopTopRight.dae"
    "package://robcog/ButtonOven.dae"
;;   "package://robcog/CeilingLight.dae"
;;   "package://robcog/CharacterCamera.dae"
    "package://robcog/CooktopHeatingElementBottomLeft.dae"
    "package://robcog/CooktopHeatingElementBottomRight.dae"
    "package://robcog/CooktopHeatingElementTopLeft.dae"
    "package://robcog/CooktopHeatingElementTopRight.dae"
    "package://robcog/Cooktop.dae"
;;    "package://robcog/CupEcoOrange.dae"
    "package://robcog/CupEspresso.dae"
    "package://robcog/Cup.dae"
    "package://robcog/DiningTable.dae"
    "package://robcog/DishwasherDoorHandle.dae"
    "package://robcog/DishwasherDoor.dae"
    "package://robcog/DishwasherLowerRack.dae"
    "package://robcog/DishwasherUpperRack.dae"
    "package://robcog/Dishwasher.dae"
;;    "package://robcog/DoubleWindow.dae"
    "package://robcog/FaucetBody.dae"
    "package://robcog/FaucetHandle.dae"
    "package://robcog/FaucetSpout.dae"
    "package://robcog/ForkDessert.dae"
    "package://robcog/ForkDinner.dae"
    "package://robcog/FridgeArea.dae"
    "package://robcog/FridgeDoorBottomShelf.dae"
    "package://robcog/FridgeDoorHandle.dae"
    "package://robcog/FridgeDoorTopShelf.dae"
    "package://robcog/FridgeDoor.dae"
    "package://robcog/FridgeDrawerHandle.dae"
    "package://robcog/FridgeDrawer.dae"
    "package://robcog/FridgeGlassShelf.dae"
    "package://robcog/FridgeHumidityDrawer.dae"
    "package://robcog/FridgeShelf.dae"
    "package://robcog/Fridge.dae"
    "package://robcog/GlassRedwine.dae"
    "package://robcog/GlassRound.dae"
    "package://robcog/GlassTall.dae"
    "package://robcog/GlassWhitewine.dae"
    "package://robcog/HohesCOrange.dae"
;;    "package://robcog/IkeaBowl.dae"
    "package://robcog/IslandArea.dae"
    "package://robcog/IslandDrawerBottomLeftHandle.dae"
    "package://robcog/IslandDrawerBottomLeft.dae"
    "package://robcog/IslandDrawerBottomMiddleHandle.dae"
    "package://robcog/IslandDrawerBottomMiddle.dae"
    "package://robcog/IslandDrawerBottomRightHandle.dae"
    "package://robcog/IslandDrawerBottomRight.dae"
    "package://robcog/IslandDrawerTopLeftHandle.dae"
    "package://robcog/IslandDrawerTopLeft.dae"
    "package://robcog/IslandDrawerTopMiddleHandle.dae"
    "package://robcog/IslandDrawerTopMiddle.dae"
    "package://robcog/IslandDrawerTopRightHandle.dae"
    "package://robcog/IslandDrawerTopRight.dae"
    "package://robcog/JaNougatBits.dae"
    "package://robcog/KellogsCornFlakesOriginal.dae"
    "package://robcog/KitchenSink.dae"
    "package://robcog/KnifeButter.dae"
    "package://robcog/KnifeTable.dae"
    "package://robcog/KoellnMuesliCranberry.dae"
;;    "package://robcog/KoellnMuesliKnusperHonigNuss.dae"
;;    "package://robcog/LabFloor.dae"
;;    "package://robcog/LabWalls.dae"
;;    "package://robcog/LargeDoubleWindow.dae"
;;    "package://robcog/LargeSingleWindow.dae"
;;    "package://robcog/LeftHand.dae"
;;    "package://robcog/MilramButtermilchErdbeere.dae"
    "package://robcog/MuellerFruchtButterMilchErdbeere.dae"
    "package://robcog/MuellerFruchtButterMilchHimbeere.dae"
    "package://robcog/MuellerFruchtButterMilchMultiVitamin.dae"
    "package://robcog/MuellerReineButterMilch.dae"
    "package://robcog/OvenArea.dae"
    "package://robcog/OvenDoorHandle.dae"
    "package://robcog/OvenDoor.dae"
    "package://robcog/OvenDrawerLeftHandle.dae"
    "package://robcog/OvenDrawerLeft.dae"
    "package://robcog/OvenDrawerMiddleBottomHandle.dae"
    "package://robcog/OvenDrawerMiddleBottom.dae"
    "package://robcog/OvenDrawerMiddleTopHandle.dae"
    "package://robcog/OvenDrawerMiddleTop.dae"
    "package://robcog/OvenDrawerRightHandle.dae"
    "package://robcog/OvenDrawerRight.dae"
    "package://robcog/OvenRack.dae"
    "package://robcog/Oven.dae"
;;    "package://robcog/PlasticBlueFork.dae"
    "package://robcog/PlateClassic16.dae"
    "package://robcog/PlateClassic26.dae"
    "package://robcog/PlateClassic28.dae"
;;    "package://robcog/RightHand.dae"
    "package://robcog/Saucer.dae"
    "package://robcog/SinkAirGap.dae"
    "package://robcog/SinkArea.dae"
    "package://robcog/SinkDrawerLeftBottomHandle.dae"
    "package://robcog/SinkDrawerLeftBottom.dae"
    "package://robcog/SinkDrawerLeftMiddleHandle.dae"
    "package://robcog/SinkDrawerLeftMiddle.dae"
    "package://robcog/SinkDrawerLeftTopHandle.dae"
    "package://robcog/SinkDrawerLeftTop.dae"
    "package://robcog/SinkStrainer.dae"
    "package://robcog/SpoonDessert.dae"
    "package://robcog/SpoonSoup.dae"
    "package://robcog/TrashDrawerHandle.dae"
    "package://robcog/TrashDrawer.dae"
    "package://robcog/Tray.dae"
    "package://robcog/WasaDelicateCrisp.dae"))
